{
 "title": "Kafka Connect Dashboard for AICORE",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "connector_type",
    "label": "Connector Type",
    "query": {
     "query": "aicore_debezium_metrics_TotalNumberOfEventsSeen"
    }
   },
   {
    "name": "connector_name",
    "label": "Connector Name",
    "query": {
     "query": "aicore_debezium_metrics_TotalNumberOfEventsSeen{plugin=\"$connector_type\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kafka Connect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sink Connector Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(aicore_kafka_connect_connector_status{connector=\"s3-sink-connector\", status=\"failed\"})",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "DLQ Sink Connector Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(aicore_kafka_connect_connector_status{connector=\"s3-sink-connector-dlq\", status=\"failed\"})",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Total Tasks",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aicore_kafka_connect_connector_status{status=\"running\"})",
     "legendFormat": "Running "
    },
    {
     "expr": "sum(aicore_kafka_connect_connector_status{status=\"failed\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Connectors and their total no. of tasks",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aicore_kafka_connect_connector_status) by (connector)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Top 5 Pods with highest CPU consumption (Cpu Time / sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{namespace=\"aicore\", container=\"cp-kafka-connect-server\"}[5m])) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage trends over time (1 hour)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"aicore\", container=\"cp-kafka-connect-server\"}[1h])) by (pod)\n",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Average CPU usage over the last 5 minutes for each pod (CPU time / second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"aicore\", container=\"cp-kafka-connect-server\"}[5m])) by (pod) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current memory usage across pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"aicore\", container=\"cp-kafka-connect-server\"}) by (pod)",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  { "title": "S3 Sink Connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Tasks and Partitions assignment",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (connector_name, task) (aicore_s3_sink_partition_count) > 0",
     "legendFormat": "{{connector_name}} - Task {{task}}"
    },
    {
     "expr": "count(sum by (connector_name, task) (aicore_s3_sink_partition_count) == 0)",
     "legendFormat": "Tasks without any partitions assigned"
    }
   ]
  },
  {
   "title": "Total read records (Before transformation applied)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 49 },
   "targets": [
    {
     "expr": "sum(aicore_s3_sink_sink_record_read_total) by (connector_name)",
     "legendFormat": "{{connector_name}} "
    }
   ]
  },
  {
   "title": "Total send records (After transformation applied)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 49 },
   "targets": [
    {
     "expr": "sum(aicore_s3_sink_sink_record_send_total) by (connector_name)",
     "legendFormat": "{{connector_name}} "
    }
   ]
  },
  {
   "title": "The average per-second rate of reading messages",
   "type": "timeseries",
   "description": "The average per-second rate of reading message from kafka before any transformation",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(aicore_s3_sink_sink_record_read_rate) by (connector_name)",
     "legendFormat": "{{connector_name}} "
    }
   ]
  },
  {
   "title": "The average per-second rate of sending messages",
   "type": "timeseries",
   "description": "\t\nThe average per-second rate of reading message from kafka after all transformations",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum(aicore_s3_sink_sink_record_send_rate) by (connector_name)",
     "legendFormat": "{{connector_name}} "
    }
   ]
  },
  {
   "title": "Active in-flight message",
   "type": "timeseries",
   "description": "\t\nActive in-flight message that haven't been committed to s3 bucket yet\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(aicore_s3_sink_sink_record_active_count) by (connector_name)",
     "legendFormat": "{{connector_name}} "
    }
   ]
  },
  {
   "title": "AVG Active in-flight message per second",
   "type": "timeseries",
   "description": "\t\nPer second average of in flight messages \n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(aicore_s3_sink_sink_record_active_count_avg) by (connector_name)",
     "legendFormat": "{{connector_name}} "
    }
   ]
  }
 ]
}