---

extends: default

rules:
  comments: disable
  document-start: disable
  line-length: disable
  indentation:
    indent-sequences: consistent
  new-line-at-end-of-file: disable

ignore:
  - .github/