{{- if and .Values.prometheus.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cp-kafka-connect.fullname" . }}-jmx-configmap
  labels:
    app: {{ template "cp-kafka-connect.name" . }}
    chart: {{ template "cp-kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  jmx-kafka-connect-prometheus.yml: |+
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.jmx.port }}/jmxrmi
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false
    ssl: false
    whitelistObjectNames:
      - kafka.connect:*
      - debezium.*:*
      - io.confluent.*:*
    rules:
      # Kafka Connect worker metrics
      - pattern: "kafka.connect<type=connect-worker-metrics>([^:]+)"
        name: aicore_kafka_connect_worker_$1
        type: GAUGE
        labels: {}

      # Kafka Connect connector metrics
      - pattern: "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
        name: aicore_kafka_connect_metrics_$2
        type: GAUGE
        labels:
          client: "$1"

      # Connector and task status metrics
      - pattern: "kafka.connect<type=connector-task-metrics, connector=([^:]+), task=([^:]+)><>status: ([^:]+)"
        name: aicore_kafka_connect_connector_status
        type: GAUGE
        value: 1
        labels:
          connector: "$1"
          task: "$2"
          status: "$3"

      # Generic connector metrics (captures both S3 and other connectors)
      - pattern: "kafka.connect<type=connector-metrics, connector=([^:]+)><>([^:]+)"
        name: aicore_kafka_connect_connector_$2
        type: GAUGE
        labels:
          connector: "$1"
          name: "$1"

      # Task-level metrics for all connectors
      - pattern: "kafka.connect<type=connector-task-metrics, connector=([^:]+), task=([^:]+)><>([^:]+)"
        name: aicore_kafka_connect_task_$3
        type: GAUGE
        labels:
          connector: "$1"
          task: "$2"
          name: "$1"

      # S3 Sink specific metrics
      - pattern: "kafka.connect<type=sink-task-metrics, connector=([^:]+), task=([^:]+)><>([^:]+)"
        name: aicore_s3_sink_$3
        type: GAUGE
        labels:
          connector: "$1"
          task: "$2"
          connector_name: "$1"

      # Debezium source metrics
      - pattern: "kafka.connect<type=connector-metrics, connector=([^:]+)><>([^:]+)"
        name: aicore_debezium_metrics_$2
        type: GAUGE
        labels:
          connector: "$1"
          name: "$1"

      - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+), key=([^>]+)><>RowsScanned"
        name: aicore_debezium_rows_scanned
        type: COUNTER
        labels:
          plugin: "$1"
          context: "$2"
          table: "$4"
          name: "debezium-connector-$3"

      - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^>]+)>([^:]+)"
        name: aicore_debezium_metrics_$4
        type: GAUGE
        labels:
          plugin: "$1"
          context: "$2"
          name: "debezium-connector-$3"

      # Streaming metrics
      - pattern: "debezium.([^:]+)<type=connector-metrics, server=([^,]+), task=([^>]+)><>([^:]+)"
        name: aicore_debezium_streaming_$4
        type: GAUGE
        labels:
          plugin: "$1"
          task: "$3"
          name: "debezium-connector-$2"

      # Queue metrics
      - pattern: "debezium.([^:]+)<type=connector-metrics, server=([^,]+), task=([^>]+)><>QueueTotalCapacity"
        name: aicore_debezium_queue_capacity_total
        type: GAUGE
        labels:
          plugin: "$1"
          task: "$3"
          name: "debezium-connector-$2"

      - pattern: "debezium.([^:]+)<type=connector-metrics, server=([^,]+), task=([^>]+)><>QueueRemainingCapacity"
        name: aicore_debezium_queue_remaining_capacity
        type: GAUGE
        labels:
          plugin: "$1"
          task: "$3"
          name: "debezium-connector-$2"

      # Table-specific event metrics
      - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+), table=([^>]+)><>NumberOfEvents"
        name: aicore_debezium_table_events_total
        type: COUNTER
        labels:
          plugin: "$1"
          context: "$2"
          table: "$4"
          name: "debezium-connector-$3"

      - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+), table=([^>]+)><>CaptureState"
        name: aicore_debezium_table_capture_state
        type: GAUGE
        labels:
          plugin: "$1"
          context: "$2"
          table: "$4"
          name: "debezium-connector-$3"

      - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+), table=([^>]+)><>LastEvent"
        name: aicore_debezium_table_last_event_timestamp
        type: GAUGE
        labels:
          plugin: "$1"
          context: "$2"
          table: "$4"
          name: "debezium-connector-$3"

{{- end }}
