name: Ingestion Engine E2E Test

on:
  workflow_dispatch:

jobs:
  kind-e2e:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --client

    - name: Install KIND
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create KIND Cluster
      run: kind create cluster --wait 120s

    - name: Build Kafka Connect Image
      uses: docker/build-push-action@v5
      with:
        context: resources/kafka-connect
        load: true
        tags: kafka-connect-custom:e2e-test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build E2E Test Image
      uses: docker/build-push-action@v5
      with:
        context: platform/test/e2e-testing
        load: true
        tags: python:e2e-test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Load Docker Images into KIND
      run: |
        kind load docker-image kafka-connect-custom:e2e-test python:e2e-test
        kubectl get nodes;

    # - name: Deploy Components
    #   run: |
    #     kubectl apply -f platform/test/e2e-testing/minikube/minio.yaml;
    #     kubectl apply -f platform/test/e2e-testing/minikube/kafka-core.yaml;
    #     kubectl apply -f platform/test/e2e-testing/minikube/kafka-connect.yaml;

    - name: Deploy test components
      shell: bash
      run: "platform/test/e2e-testing/scripts/init-minikube.sh"
    
    - name: Running tests
      shell: bash
      run: "platform/test/e2e-testing/scripts/run-e2e-test.sh"