name: Deploy Online Feature Store

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: local
        type: choice
        options:
          - local
          - prod
          - sandbox
          - staging
          - ws2-aicore
      image_tag:
        description: 'Image tag to update (e.g., v0.0.6)'
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  Deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set environment file name
        id: set_env
        run: |
          echo "ENV_FILE=helm-chart/values-${{ github.event.inputs.environment }}.yaml" >> $GITHUB_ENV

      - name: Update image tag in ${{ env.ENV_FILE }}
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq e -i '.image.tag = "v${{ inputs.image_tag }}"' $ENV_FILE

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git add $ENV_FILE
          git commit -m "Update image tag to ${{ inputs.image_tag }} for ${{ inputs.environment }} (triggered by ${{ github.actor }})"
          git push
    