name: YAML Lint

on:
  pull_request:

jobs:
  yaml_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get list of changed YAML and JSON files
        id: changed
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep -E '\.ya?ml$|\.json$' || true)
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Install linters
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Lint YAML files
        if: steps.changed.outputs.changed_files != ''
        run: |
          echo "${{ steps.changed.outputs.changed_files }}" |
            grep -E '\.ya?ml$' \
            | xargs -r -n1 bash -c '
              if [ -f "$1" ]; then
              yamllint "$1"
            else
              echo "Skipping missing file: $1"
            fi
            ' _
