apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Release.Name }}
spec:
  generators:
  - list:
      elements:
      -  name: aicore-ingestion-engine
         chartName: aicore-ingestion-engine
         version: {{ default .Chart.Version }}
         namespace: aicore
  template:
    metadata:
      name: '{{ "{{name}}" }}'
    spec:
      project: aicore
      source:
        repoURL:  https://charts.xcloudiq.com/charts/aicore
        chart: {{`'{{chartName}}'`}}
        targetRevision: {{`'{{version}}'`}}
        plugin:
          name: argocd-vault-plugin-helm
          env:
            - name: CONFIG_REPO_URL
              value: git@github.com:extremenetworks
            - name: CONFIG_REPO_NAME
              value: {{ .Values.configRepoName }}
            - name: CONFIG_REPO_KEY
              value: {{ .Values.configRepoName | upper | replace "-" "_" }}_KEY
            - name: CONFIG_BRANCH
              value: {{ .Values.configBranch }}
            - name: CONFIG_BASE
              value: {{ .Release.Name }}
            - name: GLOBAL_VALUES
              value: {{ .Release.Name }}/{{ .Values.cluster_name }}/global.yaml
            - name: APP_VALUES
              value: {{ .Release.Name }}/{{ .Values.cluster_name }}/{{`{{name}}`}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ "{{namespace}}" }}'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - FailFast=true  # enable global FailFast, so any step will stop when fail
